package com.validator.semantic;

/**
 * Represents the type of a SysML v2 element.
 * These correspond to the major element types in the SysML v2 metamodel.
 */
public enum ElementType {
    // Structure elements
    PACKAGE,
    PART_DEFINITION,
    PART_USAGE,
    ATTRIBUTE_DEFINITION,
    ATTRIBUTE_USAGE,
    PORT_DEFINITION,
    PORT_USAGE,
    INTERFACE_DEFINITION,
    INTERFACE_USAGE,
    CONNECTION_DEFINITION,
    CONNECTION_USAGE,
    BINDING_DEFINITION,
    BINDING_USAGE,
    ITEM_DEFINITION,
    ITEM_USAGE,

    // Behavior elements
    ACTION_DEFINITION,
    ACTION_USAGE,
    STATE_DEFINITION,
    STATE_USAGE,
    TRANSITION,

    // Requirements
    REQUIREMENT_DEFINITION,
    REQUIREMENT_USAGE,

    // Analysis & Verification
    ANALYSIS_DEFINITION,
    CALC_DEFINITION,
    CALC_USAGE,
    VERIFICATION_DEFINITION,
    VERIFICATION_USAGE,
    CONSTRAINT_DEFINITION,
    CONSTRAINT_USAGE,

    // Allocation
    ALLOCATION_DEFINITION,
    ALLOCATION_USAGE,

    // Views & Rendering
    VIEW_DEFINITION,
    VIEW_USAGE,
    VIEWPOINT_DEFINITION,
    RENDERING_DEFINITION,
    RENDERING_USAGE,

    // Metadata
    METADATA_DEFINITION,
    COMMENT,
    DOCUMENTATION,

    // Use Cases
    USE_CASE_DEFINITION,
    USE_CASE_USAGE,
    ACTOR_DEFINITION,
    STAKEHOLDER_DEFINITION,

    // Occurrence & Time
    OCCURRENCE_DEFINITION,
    OCCURRENCE_USAGE,
    INDIVIDUAL,
    SNAPSHOT,
    TIMESLICE,

    // Data Types
    DATA_TYPE,
    ENUMERATION_DEFINITION,
    ENUMERATION_VALUE,
    ENUMERATION,

    // KerML Foundation Types
    CLASS_DEFINITION,
    CLASS_USAGE,
    STRUCT_DEFINITION,
    STRUCT_USAGE,
    ASSOCIATION_DEFINITION,
    ASSOCIATION_USAGE,
    BEHAVIOR_DEFINITION,
    BEHAVIOR_USAGE,
    FUNCTION_DEFINITION,
    FUNCTION_USAGE,
    PREDICATE_DEFINITION,
    PREDICATE_USAGE,
    INTERACTION_DEFINITION,
    INTERACTION_USAGE,
    METACLASS_DEFINITION,
    CLASSIFIER_DEFINITION,
    CLASSIFIER_USAGE,
    TYPE_DEFINITION,
    TYPE_USAGE,
    FEATURE_DEFINITION,
    FEATURE_USAGE,
    CONNECTOR_DEFINITION,
    CONNECTOR_USAGE,
    DATATYPE_DEFINITION,
    DATATYPE_USAGE,
    MULTIPLICITY_RANGE,
    STEP_DEFINITION,
    STEP_USAGE,

    // Relationships
    SPECIALIZATION,
    REDEFINITION,
    SUBSETTING,
    FEATURE_TYPING,
    CONJUGATION,
    DEPENDENCY,

    // Other
    IMPORT,
    FEATURE_MEMBERSHIP,
    EXPRESSION,
    LITERAL,
    UNKNOWN
}
